# Site settings
title: Compiler Teaching Resources
author: David Chisnall
url: "http://compilerteaching.github.io" 
createdyear: 2014
# Build settings
markdown: kramdown
kramdown: 
  toc_levels: "2,3" 
